services:
    - docker

env:
    - DOCKER_COMPOSE_VERSION=1.22.0

before_install:
    - docker -v
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - which docker-compose
    - docker-compose --version

before_script:
    - docker-compose build
    - docker-compose run web rake db:create
    - docker-compose up -d

script: # tests here
    - docker ps

after_script:
    - docker-compose down
